simple_social_clone/simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^$",views.about,name='about'),

]

simple_social_clone/simplesocial/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"^new/$", views.CreatePost.as_view(), name="create"),
    url(r"^by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simple_social_clone/simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^$",include('accounts.urls'),name='about'),
]

simple_social_clone/simplesocial/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- <link rel="stylesheet" href="css/master.css"> -->

  <!-- card links -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> -->


<div class="container">

<div class="card text-center">
  <div class="card-header">


  <h2 style="color:grey">MyProfile</h2><br>

  <div style="color:grey" class="card-body">

    <img src="{% static 'images/p3.jpg' %}" class='img-circle' width='200px' height='200px' alt="">
      <h3 class="card-title"><b>Syed Saheel Ahmed</b></h3>
    <h4 class="card-text">Full Stack WebDeveloper & Python Developer</h4>
    <p>Final Year-(B.E),Specialized in CSE.</p>
    <p><small>Connect me at: <a href="https://www.github.com/Saheel316">Github</a></small></p>
    <a href="#" class="btn btn-primary">Know More</a>
    <div class="card-footer text-muted">
      <small>Last Updated 1month ago..</small>
    </div>

  </div>


</div>
</div>
</div>




{% endblock %}

simple_social_clone/simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>Star Social</title>
  <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">




  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">



</head>



  <body class='loader'>

  <nav class="navbar navbar-expand-lg navbar-inverse " id='one'>
      <div class="container-fluid">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
              </button>


                 <a class='navbar-brand bigbrand' id='pp' href="{% url 'home' %}">
                   <img src="{% static 'images/4.jpg' %}" class='img-circle' width="60px" height="60px" alt=""></a>

             </div>

             <ul class="nav navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'accounts:about' %}"><b>Profile</b></a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.github.com"><b>Github</b></a></li>
            </ul>

              <div class="collapse navbar-collapse" id="myNavbar">

    					<ul class="nav navbar-nav navbar-right" id='bold-li'>




    						{% if user.is_authenticated %}
                      <li class='nav-item'><a class='nav-link' href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li calss='nav-item'><a class='nav-link' href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li class='nav-item'><a class='nav-link' href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li class='nav-item'><a class='nav-link' href="{% url 'accounts:logout' %}" class="btn btn-simple"><span class='glyphicon glyphicon-off'></a></li>
    						{% else %}
    						      <li class='nav-item'><a  href="{% url 'groups:all' %}" data-toggle="tooltip" data-placement="bottom" title="Login_To_Create" class="nav-link btn btn-simple "><b> Groups</b></a></li>
                         <li class='nav-item'><a  href="{% url 'accounts:signup' %}" class="nav-link btn btn-simple"><span class='glyphicon glyphicon-user '></span><b> Sign Up</b></a></li>

                      <li class='nav-item'><a data-toggle="tooltip" data-placement="top" title="login here" href="{% url 'accounts:login' %}" class='nav-link btn btn-simple' ><span class='glyphicon glyphicon-log-in '><b> Login</b></span></a></li>

    						{% endif %}
    					</ul>
            </div>
          </div>

    		</nav>


  <!-- Footer -->
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>




  </body>


   <!-- <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
</html>

simple_social_clone/simplesocial/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- <link rel="stylesheet" href='/css/master.css'"> -->

<div class="container">

    <h1 style="color:white">Welcome to Mysterious World..!!</h1>
    <p style="color:grey">Get connected and explore new things </p>
    <h3 style='color:white'>Login or Sign-up for free to get started!</h3>
</div>



{% endblock %}

simple_social_clone/simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

simple_social_clone/simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1 style="text-align:center">Thanks for visiting!</h1>
<p style="text-align:center">
   Come back soon!</p>

{% endblock %}